set -g mouse on
set -g set-clipboard on
set -s copy-command 'pbcopy'
# 'R' でセッション名を変更し、かつ永続化（destroy-unattached off）する
bind-key R command-prompt -I "#S" "rename-session '%%'; set-option destroy-unattached off; display-message 'Session saved & persisted!'"
set-window-option -g mode-keys vi
bind r source-file ~/.tmux.conf \; display "Reloaded!"
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel
# Prefix + Ctrl-l で画面クリア ＆ スクロール履歴も完全に消去する
bind C-l send-keys -R \; send-keys C-l \; clear-history \; display "Cleared history!"
bind -T copy-mode-vi WheelUpPane send-keys -X scroll-up
bind -T copy-mode-vi WheelDownPane send-keys -X scroll-down
