set -g mouse on
set -g set-clipboard on
if-shell "uname | grep -q Darwin" \
  "set -s copy-command 'pbcopy'" \
  "set -s copy-command 'wl-copy'"
# 'R' でセッション名を変更し、かつ永続化（destroy-unattached off）する
bind-key R command-prompt -I "#S" "rename-session '%%'; set-option destroy-unattached off; display-message 'Session saved & persisted!'"
set-window-option -g mode-keys vi
bind r source-file ~/.tmux.conf \; display "Reloaded!"
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel
# Prefix + Ctrl-l で画面クリア ＆ スクロール履歴も完全に消去する
bind C-l send-keys -R \; send-keys C-l \; clear-history \; display "Cleared history!"
bind -T copy-mode-vi WheelUpPane send-keys -X scroll-up
bind -T copy-mode-vi WheelDownPane send-keys -X scroll-down
set -g allow-passthrough on
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'
# Vimのキーバインドでペインを移動
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
# 非アクティブなペインの境界線を暗いグレーに
set -g pane-border-style "fg=#444444"
# アクティブなペインの境界線を明るい白にして太字(bold)にする
set -g pane-active-border-style "fg=#ffffff,bold"
# アクティブpaneの色
set -g window-active-style 'fg=colour250,bg=black'
# 非アクティブpaneの色
set -g window-style 'fg=colour239,bg=colour234,dim'
# 分割先でディレクトリパスを引き継ぐ 
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
# 新規ウィンドウ先でディレクトリパスを引き継ぐ
bind c new-window -c "#{pane_current_path}"
set -g default-command "exec fish"
